dataset: 'gather3d'
sync_method: loose
coarse: True
verbose: False
meshing:
  depth_test: True
  get_largest_components: True
  # resolution: 256
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.003
  pixels: 200
  iters: 50
mapping:
  every_frame: 5
  vis_freq: 50
  vis_inside_freq: 30
  mesh_freq: 50
  ckpt_freq: 50
  keyframe_every: 50
  mapping_window_size: 10
  pixels: 5000
  iters_first: 1500
  iters: 60
  bound: [[-5.0,1.5],[-2.0,2.0],[-5.0,2.5]]
  marching_cubes_bound: [[-5.0,1.5],[-2.0,2.0],[-5.0,2.5]]
cam: 
  H: 480 
  W: 640
  fx: 484.527
  fy: 484.527
  cx: 321.401
  cy: 228.276
  png_depth_scale: 4095.9375 #for depth image in png format
  crop_edge: 0
data:
  input_folder: Datasets/office
  output: output/office